<a href="https://colab.research.google.com/github/fboldt/aulasann/blob/main/aula2a_matrizes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a = np.array(range(12))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
A = a.reshape(4,-1)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
a.shape, A.shape

((12,), (4, 3))

In [14]:
B = np.array(range(6)).reshape(-1,3)
B

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
b = B[0]
b

array([0, 1, 2])

In [17]:
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
b * A

array([[ 0,  1,  4],
       [ 0,  4, 10],
       [ 0,  7, 16],
       [ 0, 10, 22]])

In [21]:
np.array(range(4)) * A.T


array([[ 0,  3, 12, 27],
       [ 0,  4, 14, 30],
       [ 0,  5, 16, 33]])

In [23]:
b.reshape(1,-1) * A

array([[ 0,  1,  4],
       [ 0,  4, 10],
       [ 0,  7, 16],
       [ 0, 10, 22]])

In [27]:
B[0], B[0:1]

(array([0, 1, 2]), array([[0, 1, 2]]))

In [28]:
B[0].shape, B[0:1].shape

((3,), (1, 3))

In [30]:
C = np.array(range(8)).reshape(4,-1)
C

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [31]:
A, B

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[0, 1, 2],
        [3, 4, 5]]))

In [33]:
A @ B.T

array([[  5,  14],
       [ 14,  50],
       [ 23,  86],
       [ 32, 122]])

In [35]:
B @ A.T == (A @ B.T).T

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [36]:
A, C

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]))

In [37]:
A.T @ C

array([[ 84, 102],
       [ 96, 118],
       [108, 134]])

In [39]:
C.T @ A == (A.T @ C).T

array([[ True,  True,  True],
       [ True,  True,  True]])

In [40]:
A.shape, B.shape, C.shape

((4, 3), (2, 3), (4, 2))

In [41]:
A @ B.T @ C.T

array([[  14,   52,   90,  128],
       [  50,  178,  306,  434],
       [  86,  304,  522,  740],
       [ 122,  430,  738, 1046]])

In [42]:
(B @ A.T) @ C

array([[ 312,  386],
       [1176, 1448]])

In [43]:
a = A[0]
b = A[1]
a, b

(array([0, 1, 2]), array([3, 4, 5]))

In [44]:
a * b

array([ 0,  4, 10])

In [45]:
a @ b

14

In [48]:
Va = a.reshape(1,-1)
Vb = b.reshape(1,-1)
Va.shape, Vb.shape

((1, 3), (1, 3))

In [52]:
Va, Vb.T

(array([[0, 1, 2]]),
 array([[3],
        [4],
        [5]]))

In [50]:
Va @ Vb.T

array([[14]])

In [53]:
Va.T @ Vb

array([[ 0,  0,  0],
       [ 3,  4,  5],
       [ 6,  8, 10]])